
# ###REQUESTS FROM CLIENT APP


# ###GET req
# get http://localhost:3000/user-api/users

# ###get a user by id
# get http://localhost:3000/user-api/users/1

# ###POST req
# post http://localhost:3000/user-api/user
# Content-Type: application/json

# {
#     "id":2,
#     "name":"bhyanu",
#     "age":35
# }



# ###PUT req
# put http://localhost:3000/user-api/user
# Content-Type: application/json

# {
#     "id":1,
#     "name":"vikas kumar",
#     "age":35
# }



# ###DELETE req
# delete http://localhost:3000/user-api/users/20



# ###PRODUCT reqs


# get http://localhost:3000/product-api/products

# ###get a user by id
# get http://localhost:3000/product-api/products/1

# ###create a user
# post http://localhost:3000/product-api/products 
# Content-Type: application/json

# {
#     "id":1,
#     "name":"clothes"
# }


# ###update a product
# put http://localhost:3000/product-api/products
# Content-Type:application/json

# {
#     "id":1,
#     "name":"jeans"
# }

###register
post http://localhost:8000/api/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "PhoneNumber": "1234567890",
  "password": "securepassword"
}


###adding new trip
post http://localhost:8000/api/trips
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0MyIsImVtYWlsIjoiZGV2QGdtYWlsLmNvbSIsImlhdCI6MTczMjM0MTc1Mn0.a31-CDhUQ5Xq0YzWZhLQCAOz4pHna8ToWZnzUC02YSM

{
  "budget": "21345678",
  "description": "zefrxctgbihjotfdtfghj",
  "endDate": "2024-11-30",
  "location": "sgfhkjl",
  "startDate": "1111-11-11",
  "title": "qwertyuio"
}